[project]
name = "TypedConf"
version = "0.1.0"
description = "A lightweight, type-safe configuration management library for Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "pip>=25.1.1",
    "pydantic>=2.11.7",
    "pytest>=9.0.3",
    "tomli-w>=1.2.0",
]


[tool.pylint.format]
max-line-length = 180

[tool.hatch.build.targets.wheel]
packages = ["src/typedconfig"]
