[project]
name = "typed-config"
version = "0.1.0"
description = "Type-Save Configuration for python."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=6.29.5",
    "pip>=25.1.1",
    "pydantic>=2.11.7",
]

[project.optional-dependencies]
extra = [
    "rich>=14.0.0",
    "tomli-w>=1.2.0",
]

[tool.pylint.format]
max-line-length = 180
